# Generated by Django 5.0.3 on 2024-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spritlep', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='FullName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
